# Generated by Django 5.2.15 on 2026-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discovery_location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_genres',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
