# Generated by Codex on 2026-06-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_discovery_location_user_favorite_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='beta_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_beta_tester',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BetaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('setup', 'Account setup'), ('navigation', 'Navigation'), ('content', 'Content and posting'), ('payments', 'Payments and support'), ('other', 'Other')], default='navigation', max_length=40)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('blocker', 'Blocker')], default='medium', max_length=40)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('summary', models.CharField(max_length=180)),
                ('details', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
