# Generated by Django 5.2.15 on 2026-06-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_share_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('fan', 'Fan'), ('artist', 'Artist'), ('host', 'Host'), ('admin', 'Admin')], default='fan', max_length=20),
        ),
    ]
