# Generated by Django 5.2.15 on 2026-06-14 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('audio_file', models.FileField(upload_to='music/')),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='cover_art/')),
                ('genre', models.CharField(blank=True, max_length=80)),
                ('bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('is_downloadable', models.BooleanField(default=False)),
                ('is_subscriber_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
