# Generated by Django 5.2.15 on 2026-06-19 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0006_musicupload_preview_defaults_and_profession_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicupload',
            name='ai_disclosure_level',
            field=models.CharField(choices=[('human_made', 'Human-made'), ('ai_assisted', 'AI-assisted'), ('ai_collaborative', 'AI-collaborative'), ('ai_generated', 'Fully AI-generated')], default='human_made', max_length=40),
        ),
        migrations.AddField(
            model_name='musicupload',
            name='ai_disclosure_note',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='AiReviewFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review_flags', to='mediahub.musicupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
