# Generated by Django 5.2.15 on 2026-06-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_phase5_push_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post', 'Post'), ('music', 'Music'), ('store', 'Store'), ('live', 'Live'), ('comment', 'Comment'), ('supporter', 'Supporter'), ('gig', 'Gig'), ('purchase', 'Purchase'), ('promotion', 'Promotion'), ('system', 'System')], default='system', max_length=40),
        ),
    ]
