# Generated by Django 6.0.8 on 2026-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post', 'Post'), ('music', 'Music'), ('store', 'Store'), ('live', 'Live'), ('comment', 'Comment'), ('supporter', 'Supporter'), ('gig', 'Gig'), ('purchase', 'Purchase'), ('promotion', 'Promotion'), ('message', 'Message'), ('system', 'System')], default='system', max_length=40),
        ),
    ]
