# Generated by Django 5.2.15 on 2026-06-19 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livehub', '0001_initial'),
        ('mediahub', '0006_musicupload_preview_defaults_and_profession_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistCalendarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('music', 'Music'), ('visual_art', 'Painting / Drawing'), ('digital_art', 'Digital Art'), ('craft', 'Crafts'), ('writing', 'Writing'), ('performance', 'Performance'), ('other', 'Other')], default='music', max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('release', 'Release'), ('live', 'Live'), ('gig', 'Gig'), ('pov', 'Point of View'), ('other', 'Other')], default='other', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('supporters', 'Supporters'), ('public', 'Public')], default='private', max_length=20)),
                ('supporter_early_hours', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_items', to=settings.AUTH_USER_MODEL)),
                ('live_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_items', to='livehub.livesession')),
                ('music_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_items', to='mediahub.musicupload')),
            ],
            options={
                'ordering': ['starts_at', 'created_at'],
                'indexes': [models.Index(fields=['artist', 'starts_at'], name='artistcalen_artist__160010_idx'), models.Index(fields=['visibility', 'starts_at'], name='artistcalen_visibil_e7380b_idx')],
            },
        ),
    ]
