# Generated by Django 5.2.15 on 2026-06-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistcalendar', '0002_alter_artistcalendaritem_profession'),
        ('spaces', '0002_phase7_8_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistcalendaritem',
            name='space_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_item', to='spaces.spacebooking'),
        ),
    ]
