# Generated by Django 5.2.15 on 2026-06-14 07:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fansubscription',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.AddField(
            model_name='fansubscription',
            name='artist_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.90'), max_digits=8),
        ),
        migrations.AddField(
            model_name='fansubscription',
            name='billing_date',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fansubscription',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=8),
        ),
    ]
