# Generated by Django 5.2.15 on 2026-06-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_created_at_fansubscription_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fansubscription',
            name='payment_provider',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='fansubscription',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fansubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fansubscription',
            name='stripe_status',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='fansubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
