# Generated by Django 5.2.15 on 2026-06-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_supporttier_fansubscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fansubscription',
            name='profession',
            field=models.CharField(choices=[('music', 'Music'), ('visual_art', 'Painting / Drawing'), ('digital_art', 'Digital Art'), ('craft', 'Crafts'), ('writing', 'Writing'), ('performance', 'Performance'), ('comedy', 'Comedian'), ('podcast', 'Podcaster'), ('film', 'Filmmaker / Video'), ('other', 'Other')], default='music', max_length=40),
        ),
        migrations.AlterField(
            model_name='onetimetip',
            name='profession',
            field=models.CharField(choices=[('music', 'Music'), ('visual_art', 'Painting / Drawing'), ('digital_art', 'Digital Art'), ('craft', 'Crafts'), ('writing', 'Writing'), ('performance', 'Performance'), ('comedy', 'Comedian'), ('podcast', 'Podcaster'), ('film', 'Filmmaker / Video'), ('other', 'Other')], default='music', max_length=40),
        ),
        migrations.AlterField(
            model_name='supporttier',
            name='profession',
            field=models.CharField(choices=[('music', 'Music'), ('visual_art', 'Painting / Drawing'), ('digital_art', 'Digital Art'), ('craft', 'Crafts'), ('writing', 'Writing'), ('performance', 'Performance'), ('comedy', 'Comedian'), ('podcast', 'Podcaster'), ('film', 'Filmmaker / Video'), ('other', 'Other')], default='music', max_length=40),
        ),
    ]
