# Generated by Django 5.2.15 on 2026-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='comment_mode',
            field=models.CharField(choices=[('anyone', 'Anyone'), ('followers_subscribers', 'Followers and Subscribers'), ('subscribers_only', 'Subscribers Only')], default='subscribers_only', max_length=40),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='livestream_mode',
            field=models.CharField(choices=[('public', 'Entire Stream Public'), ('public_10', 'Public Preview - 10 Minutes'), ('public_30', 'Public Preview - 30 Minutes'), ('public_60', 'Public Preview - 60 Minutes'), ('subscribers_only', 'Subscribers Only From Start')], default='public_30', max_length=40),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='influences',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
