# Generated by Django 5.2.15 on 2026-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artistfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistfollow',
            name='show_about',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artistfollow',
            name='show_lives',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artistfollow',
            name='show_music',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artistfollow',
            name='show_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artistfollow',
            name='show_store',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='show_about',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='show_lives',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='show_music',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='show_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='show_store',
            field=models.BooleanField(default=True),
        ),
    ]
