# Generated by Django 5.2.15 on 2026-06-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_remove_artistfollow_page_builder_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='comment_mode',
            field=models.CharField(choices=[('anyone', 'Anyone'), ('followers_subscribers', 'Supporters'), ('subscribers_only', 'Subscribers Only')], default='subscribers_only', max_length=40),
        ),
    ]
