# Generated by Django 5.2.15 on 2026-06-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_alter_artistprofile_comment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
