# Generated by Django 5.2.15 on 2026-06-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_artistprofile_instagram_url_artistprofile_tiktok_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='instagram_reach',
            field=models.CharField(blank=True, help_text='e.g. 10.5k followers', max_length=40),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='tiktok_reach',
            field=models.CharField(blank=True, help_text='e.g. 200k followers', max_length=40),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='website_label',
            field=models.CharField(blank=True, help_text='e.g. Official Site', max_length=40),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='youtube_reach',
            field=models.CharField(blank=True, help_text='e.g. 50k subscribers', max_length=40),
        ),
    ]
