# Generated by Django 5.2.15 on 2026-06-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0014_alter_artistprofessionprofile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='stripe_connect_onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
