# Generated by Django 5.2.15 on 2026-06-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0015_phase4_stripe_connect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='instagram_reach',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='tiktok_reach',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='youtube_reach',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='youtube_channel_id',
            field=models.CharField(blank=True, help_text='Resolved from the YouTube URL', max_length=64),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='youtube_reach_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='youtube_subscriber_count',
            field=models.BigIntegerField(blank=True, help_text='Platform-verified subscriber count from the YouTube Data API', null=True),
        ),
    ]
