# Generated by Django 5.2.15 on 2026-06-21 09:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('aliases', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('track', 'Track'), ('post', 'Post'), ('product', 'Merch / product'), ('profile', 'Artist profile'), ('livestream', 'Live stream')], default='track', max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=8)),
                ('spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft (awaiting payment)'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('target_genres', models.CharField(blank=True, default='', max_length=255)),
                ('target_location', models.CharField(blank=True, default='', max_length=120)),
                ('target_artist_ids', models.CharField(blank=True, default='', max_length=255)),
                ('discovery_score', models.FloatField(default=0.0)),
                ('payment_provider', models.CharField(blank=True, default='', max_length=40)),
                ('stripe_checkout_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('full_listen', 'Full listen'), ('save', 'Save'), ('follow', 'Follow'), ('share', 'Share'), ('purchase', 'Purchase'), ('feedback_up', 'Would listen again'), ('feedback_down', 'Not for me')], max_length=20)),
                ('charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='promotions.campaign')),
                ('fan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('purchase', 'Credit purchase'), ('grant', 'Plan grant'), ('spend', 'Campaign spend'), ('reward', 'Discovery reward'), ('refund', 'Campaign refund'), ('redeem', 'Credit redeemed')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='promotions.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'target_type', 'target_id'], name='promotions__status_b9b0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['artist', 'status'], name='promotions__artist__a02aac_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignevent',
            index=models.Index(fields=['campaign', 'event_type'], name='promotions__campaig_45a456_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignevent',
            index=models.Index(fields=['campaign', 'fan', 'event_type'], name='promotions__campaig_1f2f01_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionledgerentry',
            index=models.Index(fields=['user', 'created_at'], name='promotions__user_id_5e643d_idx'),
        ),
    ]
