# Generated by Django 5.2.15 on 2026-06-19 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('capacity', models.PositiveSmallIntegerField(default=20)),
                ('available_windows', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('bar_open', models.BooleanField(default=True)),
                ('kitchen_open', models.BooleanField(default=False)),
                ('kitchen_notes', models.CharField(blank=True, max_length=255)),
                ('drink_minimum', models.CharField(blank=True, max_length=120)),
                ('last_call', models.CharField(blank=True, max_length=80)),
                ('split_type', models.CharField(choices=[('door_percent', 'Door percent'), ('flat_fee', 'Flat fee'), ('fb_only', 'F&B only')], default='door_percent', max_length=20)),
                ('host_cut_percent', models.PositiveSmallIntegerField(default=20)),
                ('flat_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('booking_mode', models.CharField(choices=[('request', 'Request'), ('instant_book', 'Instant book')], default='request', max_length=20)),
                ('min_local_supporters', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpaceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('expected_audience', models.PositiveSmallIntegerField(default=0)),
                ('pitch', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('linked_event_id', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_checked_in', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_bookings', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='spaces.spacelisting')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.AddIndex(
            model_name='spacelisting',
            index=models.Index(fields=['city', 'status'], name='spaces_spac_city_cf699e_idx'),
        ),
        migrations.AddIndex(
            model_name='spacelisting',
            index=models.Index(fields=['host', 'status'], name='spaces_spac_host_id_274eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='spacebooking',
            index=models.Index(fields=['listing', 'status'], name='spaces_spac_listing_4e6de5_idx'),
        ),
        migrations.AddIndex(
            model_name='spacebooking',
            index=models.Index(fields=['artist', 'status'], name='spaces_spac_artist__0ab807_idx'),
        ),
    ]
