# Generated by Django 5.2.15 on 2026-06-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_phase3_show_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacebookingreview',
            name='reviewee_type',
            field=models.CharField(choices=[('artist', 'Artist'), ('host', 'Host'), ('show', 'Show')], max_length=20),
        ),
    ]
