# Generated by Django 5.2.15 on 2026-06-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_show_eticket_ticket_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowETicket',
        ),
    ]
