# Generated by Django 5.2.15 on 2026-06-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_remove_show_eticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacebooking',
            name='dismissed_by_artist_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spacebooking',
            name='dismissed_by_host_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
