# Generated by Django 6.0.8 on 2026-08-07 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0012_showticketstub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_follows', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='spaces.spacelisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fan', 'created_at'], name='spaces_spac_fan_id_26d059_idx'), models.Index(fields=['listing', 'created_at'], name='spaces_spac_listing_7edc36_idx')],
                'unique_together': {('fan', 'listing')},
            },
        ),
    ]
