# Generated by Django 6.0.8 on 2026-08-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0012_showticketstub'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacebooking',
            name='supporter_presale_hours',
            field=models.PositiveSmallIntegerField(default=0, help_text="Hours after tickets go on sale during which only the artist's supporters can buy."),
        ),
        migrations.AddField(
            model_name='spacebooking',
            name='tickets_on_sale_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
