# Generated by Django 5.2.15 on 2026-06-28 17:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('campaign_type', models.CharField(choices=[('new_song', 'New song'), ('album', 'Album'), ('artist_page', 'Artist page'), ('merch', 'Merch'), ('show', 'Show'), ('video', 'Video')], default='new_song', max_length=40)),
                ('goal', models.CharField(choices=[('more_streams', 'More streams'), ('new_followers', 'New followers'), ('email_signups', 'Email signups'), ('merch_sales', 'Merch sales'), ('ticket_sales', 'Ticket sales'), ('video_views', 'Video views')], default='more_streams', max_length=40)),
                ('ad_networks', models.JSONField(blank=True, default=list)),
                ('destination_type', models.CharField(choices=[('indiefund_page', 'IndieFund page'), ('smart_link', 'Smart link'), ('streaming_link', 'Streaming link'), ('store', 'Store'), ('signup', 'Signup page'), ('external_url', 'External URL')], default='smart_link', max_length=40)),
                ('destination_url', models.URLField(blank=True, default='', max_length=500)),
                ('budget_daily', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8)),
                ('budget_total', models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('audience_description', models.TextField(blank=True, default='')),
                ('similar_artists', models.JSONField(blank=True, default=list)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('creative_headline', models.CharField(blank=True, default='', max_length=200)),
                ('creative_text', models.TextField(blank=True, default='')),
                ('creative_file', models.FileField(blank=True, null=True, upload_to='campaigns/creatives/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('launched', 'Launched'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('follows', models.PositiveIntegerField(default=0)),
                ('subscribers', models.PositiveIntegerField(default=0)),
                ('purchases', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fan_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='campaigns.campaign')),
            ],
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['artist', 'status'], name='campaigns_c_artist__73bbd7_idx'),
        ),
    ]
