# Generated by Django 6.0.8 on 2026-08-06 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livehub', '0001_initial'),
        ('mediahub', '0009_musicupload_acoustic_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listening_parties', to='mediahub.musicupload'),
        ),
    ]
