# Generated by Django 5.2.15 on 2026-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_mode',
            field=models.CharField(choices=[('account_default', 'Use Artist Default'), ('anyone', 'Anyone'), ('followers_subscribers', 'Followers and Subscribers'), ('subscribers_only', 'Subscribers Only')], default='account_default', max_length=40),
        ),
    ]
