# Generated by Django 5.2.15 on 2026-06-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_comment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_mode',
            field=models.CharField(choices=[('account_default', 'Use Artist Default'), ('anyone', 'Anyone'), ('followers_subscribers', 'Supporters'), ('subscribers_only', 'Subscribers Only')], default='account_default', max_length=40),
        ),
    ]
