# Generated by Django 5.2.15 on 2026-06-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_comment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='post',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('music', 'Music'), ('story', 'Story'), ('live', 'Live'), ('instagram', 'Instagram Embed'), ('tiktok', 'TikTok Embed')], default='text', max_length=20),
        ),
    ]
