# Generated by Django 5.2.15 on 2026-06-15 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artistsignal',
            name='signal_type',
            field=models.CharField(choices=[('save', 'Save'), ('skip', 'Skip'), ('more_like_this', 'More Like This')], default='save', max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='artistsignal',
            unique_together={('fan', 'artist', 'signal_type')},
        ),
    ]
