# Generated by Django 5.2.15 on 2026-06-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
        migrations.AddField(
            model_name='product',
            name='bpm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_supporter_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='license_type',
            field=models.CharField(blank=True, help_text='Non-exclusive, Exclusive, Royalty-free, etc', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='music_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='preview_audio',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/previews/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_file',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/files/'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Example: S,M,L,XL', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('merch', 'Merch'), ('beat', 'Beat'), ('sample_pack', 'Sample Pack'), ('acapella', 'Acapella'), ('stems', 'Stems'), ('midi_pack', 'MIDI Pack'), ('drum_kit', 'Drum Kit'), ('preset_pack', 'Preset Pack')], default='merch', max_length=40),
        ),
    ]
