# Generated by Django 5.2.15 on 2026-06-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_seller_product_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('merch', 'Merch'), ('membership_merch', 'Membership Merch'), ('digital_download', 'Digital Download'), ('external_fulfillment', 'External Fulfillment'), ('beat', 'Beat'), ('sample_pack', 'Sample Pack'), ('acapella', 'Acapella'), ('stems', 'Stems'), ('midi_pack', 'MIDI Pack'), ('drum_kit', 'Drum Kit'), ('preset_pack', 'Preset Pack')], default='merch', max_length=40),
        ),
    ]
