# Generated by Django 5.2.15 on 2026-06-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_external_url_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eligibility_months',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
