# Generated by Django 5.2.15 on 2026-06-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_product_eligibility_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_discount_code',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
