# Generated by Django 5.2.15 on 2026-06-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_product_external_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fulfillment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fulfillment_status',
            field=models.CharField(default='not_started', max_length=40),
        ),
    ]
