# Generated by Django 5.2.15 on 2026-06-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('merch', 'Merch'), ('membership_merch', 'Membership Merch'), ('digital_download', 'Digital Download'), ('external_fulfillment', 'External Fulfillment'), ('gelato_pod', 'Gelato Print-on-Demand'), ('shopify_store', 'Shopify Store'), ('printify_pod', 'Printify Print-on-Demand'), ('fourthwall_store', 'Fourthwall Store'), ('bandcamp_store', 'Bandcamp Store'), ('printful_pod', 'Printful Print-on-Demand'), ('beat', 'Beat'), ('sample_pack', 'Sample Pack'), ('acapella', 'Acapella'), ('stems', 'Stems'), ('midi_pack', 'MIDI Pack'), ('drum_kit', 'Drum Kit'), ('preset_pack', 'Preset Pack')], default='merch', max_length=40),
        ),
    ]
