# Generated by Django 5.2.15 on 2026-07-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_product_host_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='acoustic_fingerprint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_training_consent',
            field=models.CharField(choices=[('allowed', 'Allowed'), ('not_allowed', 'Not allowed'), ('unknown', 'Unknown')], default='not_allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/downloads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='download_requires_purchase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='file_hash_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='is_master_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='master_file',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/masters/'),
        ),
        migrations.AddField(
            model_name='product',
            name='no_ai_training_notice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='public_stream_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stream_file',
            field=models.FileField(blank=True, null=True, upload_to='marketplace/streams/'),
        ),
    ]
